#Data preprocessing 

Data preprocessing is a crucial step in the machine learning pipeline. It involves cleaning the dataset, handling missing values, encoding categorical variables, detecting and handling outliers, scaling numerical features, and preparing the data for model training.

The objective of this notebook is to transform the raw dataset into a clean and machine-learning-ready format.

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

Load Dataset

In [2]:
df = pd.read_csv("placedata_v2_0_synthetic.csv")

df.head()

,StudentID,CGPA,Internships,Projects,Workshops/Certifications,AptitudeTestScore,SoftSkillsRating,ExtracurricularActivities,PlacementTraining,SSC_Marks,HSC_Marks,PlacementStatus
0,1,7.5,1,1,1,65,4.4,No,No,61,79,NotPlaced
1,2,8.9,0,3,2,90,4.0,Yes,Yes,78,82,Placed
2,3,7.3,1,2,2,82,4.8,Yes,No,79,80,NotPlaced
3,4,7.5,1,1,2,85,4.4,Yes,Yes,81,80,Placed
4,5,8.3,1,2,2,86,4.5,Yes,Yes,74,88,Placed

Check Missing Values

In [3]:
print(df.isnull().sum())

StudentID                    0
CGPA                         0
Internships                  0
Projects                     0
Workshops/Certifications     0
AptitudeTestScore            0
SoftSkillsRating             0
ExtracurricularActivities    0
PlacementTraining            0
SSC_Marks                    0
HSC_Marks                    0
PlacementStatus              0
dtype: int64

Remove Duplicate Rows

In [4]:
print("Duplicate Rows:", df.duplicated().sum())

df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

Duplicate Rows: 0
Shape after removing duplicates: (10000, 12)

Drop Student ID

In [5]:
df.drop("StudentID", axis=1, inplace=True)

df.head()

,CGPA,Internships,Projects,Workshops/Certifications,AptitudeTestScore,SoftSkillsRating,ExtracurricularActivities,PlacementTraining,SSC_Marks,HSC_Marks,PlacementStatus
0,7.5,1,1,1,65,4.4,No,No,61,79,NotPlaced
1,8.9,0,3,2,90,4.0,Yes,Yes,78,82,Placed
2,7.3,1,2,2,82,4.8,Yes,No,79,80,NotPlaced
3,7.5,1,1,2,85,4.4,Yes,Yes,81,80,Placed
4,8.3,1,2,2,86,4.5,Yes,Yes,74,88,Placed

Encode Categorical Features

In [6]:
label_encoder = LabelEncoder()

df["ExtracurricularActivities"] = label_encoder.fit_transform(
    df["ExtracurricularActivities"]
)

df["PlacementTraining"] = label_encoder.fit_transform(
    df["PlacementTraining"]
)

df["PlacementStatus"] = label_encoder.fit_transform(
    df["PlacementStatus"]
)

df.head()

,CGPA,Internships,Projects,Workshops/Certifications,AptitudeTestScore,SoftSkillsRating,ExtracurricularActivities,PlacementTraining,SSC_Marks,HSC_Marks,PlacementStatus
0,7.5,1,1,1,65,4.4,0,0,61,79,0
1,8.9,0,3,2,90,4.0,1,1,78,82,1
2,7.3,1,2,2,82,4.8,1,0,79,80,0
3,7.5,1,1,2,85,4.4,1,1,81,80,1
4,8.3,1,2,2,86,4.5,1,1,74,88,1

Handle Outliers using IQR Method

In [ ]:

label_encoder = LabelEncoder()

df["ExtracurricularActivities"] = label_encoder.fit_transform(
    df["ExtracurricularActivities"]
)

df["PlacementTraining"] = label_encoder.fit_transform(
    df["PlacementTraining"]
)

df["PlacementStatus"] = label_encoder.fit_transform(
    df["PlacementStatus"]
)

df.head()

,CGPA,Internships,Projects,Workshops/Certifications,AptitudeTestScore,SoftSkillsRating,ExtracurricularActivities,PlacementTraining,SSC_Marks,HSC_Marks,PlacementStatus
0,7.5,1,1,1,65,4.4,0,0,61,79,0
1,8.9,0,3,2,90,4.0,1,1,78,82,1
2,7.3,1,2,2,82,4.8,1,0,79,80,0
3,7.5,1,1,2,85,4.4,1,1,81,80,1
4,8.3,1,2,2,86,4.5,1,1,74,88,1

Handle Outliers using IQR Method

In [8]:
numerical_columns = [
    "CGPA",
    "Internships",
    "Projects",
    "Workshops/Certifications",
    "AptitudeTestScore",
    "SoftSkillsRating",
    "SSC_Marks",
    "HSC_Marks"
]

for col in numerical_columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df[col] = np.where(df[col] < lower, lower, df[col])
    df[col] = np.where(df[col] > upper, upper, df[col])

print("Outliers handled successfully.")

Outliers handled successfully.

Separate Features and Target

In [9]:
X = df.drop("PlacementStatus", axis=1)

y = df["PlacementStatus"]

print(X.shape)
print(y.shape)

(10000, 10)
(10000,)

Feature Scaling

In [10]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("Scaling Completed")

Scaling Completed

Train-Test Split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)

print("Training Labels :", y_train.shape)
print("Testing Labels  :", y_test.shape)

Training Features : (8000, 10)
Testing Features  : (2000, 10)
Training Labels : (8000,)
Testing Labels  : (2000,)

Save Preprocessed Data

In [12]:
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

X_train.to_csv("X_train.csv", index=False)
X_test.to_csv("X_test.csv", index=False)

y_train.to_csv("y_train.csv", index=False)
y_test.to_csv("y_test.csv", index=False)

print("Preprocessed files saved successfully.")

Preprocessed files saved successfully.

#Conclusion

The dataset was successfully preprocessed and prepared for machine learning. Missing values and duplicate records were checked, and unnecessary columns such as StudentID were removed. Categorical variables were converted into numerical form using label encoding. Outliers in the numerical features were handled using the IQR method, and feature scaling was performed using the StandardScaler to ensure all features were on a similar scale. Finally, the dataset was split into training and testing sets using an 80:20 ratio. The preprocessed data is now clean, consistent, and ready for the model development and evaluation phase.